// <auto-generated />
using System;
using FormerUrban_Afta.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormerUrban_Afta.DataAccess.Migrations
{
    [DbContext(typeof(FromUrbanDbContext))]
    [Migration("20250726081417_severalTablesEncrypted")]
    partial class severalTablesEncrypted
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.ActivityLogFilters", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<bool>("AddStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DeleteStatus")
                        .HasColumnType("bit");

                    b.Property<int>("FormName")
                        .HasColumnType("int");

                    b.Property<bool>("GetStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("UpdateStatus")
                        .HasColumnType("bit");

                    b.HasKey("Identity");

                    b.ToTable("ActivityLogFilters");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.AllowedIPRange", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Identity");

                    b.ToTable("AllowedIPRange");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.Apartman", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("C_Jahat")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MasahatArse")
                        .HasColumnType("float");

                    b.Property<double?>("MasahatKol")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoeSaze")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("asli")
                        .HasColumnType("int");

                    b.Property<int?>("azFari")
                        .HasColumnType("int");

                    b.Property<int?>("bakhsh")
                        .HasColumnType("int");

                    b.Property<int?>("c_NoeSaze")
                        .HasColumnType("int");

                    b.Property<int?>("c_noemalekiyat")
                        .HasColumnType("int");

                    b.Property<int?>("c_noesanad")
                        .HasColumnType("int");

                    b.Property<int?>("c_vazsanad")
                        .HasColumnType("int");

                    b.Property<string>("codeposti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("fari")
                        .HasColumnType("int");

                    b.Property<string>("jahat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noemalekiyat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noesanad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pelakabi")
                        .HasColumnType("int");

                    b.Property<int>("radif")
                        .HasColumnType("int");

                    b.Property<string>("sabti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("sh_Darkhast")
                        .HasColumnType("bigint");

                    b.Property<int>("shop")
                        .HasColumnType("int");

                    b.Property<int?>("tafkiki")
                        .HasColumnType("int");

                    b.Property<string>("tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vazsanad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identity");

                    b.ToTable("Apartman");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.Audit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CurrentValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Form")
                        .HasColumnType("int");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("OriginValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.AuditFilter", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Identity");

                    b.ToTable("AuditFilters");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.BlockedIPRange", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Identity");

                    b.ToTable("BlockedIPRange");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.ControlMap", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<int?>("C_NoeNama")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoeNama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoeSaze")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TedadTabaghe")
                        .HasColumnType("float");

                    b.Property<int?>("c_NoeSaze")
                        .HasColumnType("int");

                    b.Property<int?>("c_noesaghf")
                        .HasColumnType("int");

                    b.Property<double?>("masahat_b")
                        .HasColumnType("float");

                    b.Property<double?>("masahat_e")
                        .HasColumnType("float");

                    b.Property<double?>("masahat_m")
                        .HasColumnType("float");

                    b.Property<double?>("masahat_s")
                        .HasColumnType("float");

                    b.Property<string>("noesaghf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("satheshghal")
                        .HasColumnType("float");

                    b.Property<int>("sh_Darkhast")
                        .HasColumnType("int");

                    b.Property<int>("shop")
                        .HasColumnType("int");

                    b.Property<double?>("tarakom")
                        .HasColumnType("float");

                    b.HasKey("Identity");

                    b.ToTable("ControlMap");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.CostumIdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.CostumIdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.Darkhast", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<string>("CodeMeli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("c_noedarkhast")
                        .HasColumnType("int");

                    b.Property<int>("c_noemot")
                        .HasColumnType("int");

                    b.Property<string>("c_nosazi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codeposti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("moteghazi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noedarkhast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noemot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("shodarkhast")
                        .HasColumnType("int");

                    b.Property<int>("shop")
                        .HasColumnType("int");

                    b.Property<string>("tel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identity");

                    b.ToTable("Darkhast");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.Dv_karbari", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("c_karbari")
                        .HasColumnType("int");

                    b.Property<int?>("c_marhaleh")
                        .HasColumnType("int");

                    b.Property<int?>("c_noeestefadeh")
                        .HasColumnType("int");

                    b.Property<int?>("c_noesakhteman")
                        .HasColumnType("int");

                    b.Property<int?>("c_noesazeh")
                        .HasColumnType("int");

                    b.Property<int?>("c_tabagheh")
                        .HasColumnType("int");

                    b.Property<int>("d_radif")
                        .HasColumnType("int");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("karbari")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("marhaleh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("masahat_k")
                        .HasColumnType("float");

                    b.Property<string>("mtable_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noeestefadeh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noesakhteman")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noesazeh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("shop")
                        .HasColumnType("int");

                    b.Property<string>("tabagheh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tarikhehdas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identity");

                    b.ToTable("Dv_karbari");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.Dv_malekin", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<double?>("ArzeshArse")
                        .HasColumnType("float");

                    b.Property<double?>("ArzeshAyan")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("c_noemalek")
                        .HasColumnType("int");

                    b.Property<int>("d_radif")
                        .HasColumnType("int");

                    b.Property<double?>("dong_a")
                        .HasColumnType("float");

                    b.Property<double?>("dong_b")
                        .HasColumnType("float");

                    b.Property<string>("family")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("father")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("kodemeli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("meghdarsahmarse")
                        .HasColumnType("float");

                    b.Property<double?>("meghdarsahmayan")
                        .HasColumnType("float");

                    b.Property<string>("mob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mtable_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noemalek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("sahm_a")
                        .HasColumnType("float");

                    b.Property<double?>("sahm_b")
                        .HasColumnType("float");

                    b.Property<string>("sh_sh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("shop")
                        .HasColumnType("int");

                    b.Property<string>("tel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identity");

                    b.ToTable("Dv_malekin");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.Dv_savabegh", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("c_noe")
                        .HasColumnType("int");

                    b.Property<int>("d_radif")
                        .HasColumnType("int");

                    b.Property<string>("mtable_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sh_darkhast")
                        .HasColumnType("int");

                    b.Property<int>("shop")
                        .HasColumnType("int");

                    b.HasKey("Identity");

                    b.ToTable("Dv_savabegh");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.Erja", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("c_marhaleh")
                        .HasColumnType("int");

                    b.Property<int>("c_nodarkhast")
                        .HasColumnType("int");

                    b.Property<int?>("c_vaziatErja")
                        .HasColumnType("int");

                    b.Property<string>("code_nosazi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ersalkonandeh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ersalkonandeh_c")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("flag")
                        .HasColumnType("bit");

                    b.Property<string>("girandeh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("girandeh_c")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ijadkonandeh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ijadkonandeh_c")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("marhaleh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_mot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noedarkhast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saat_erja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("sh_darkhast")
                        .HasColumnType("int");

                    b.Property<double?>("shop")
                        .HasColumnType("float");

                    b.Property<string>("tarikh_darkhast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tarikh_erja")
                        .HasColumnType("int");

                    b.Property<string>("vaziatErja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identity");

                    b.ToTable("Erja");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.Estelam", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Dang_Enteghal")
                        .HasColumnType("float");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kharidar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoeMalekiat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sh_Darkhast")
                        .HasColumnType("int");

                    b.Property<string>("Sh_Pasokh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Tarikh_Pasokh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tozihat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("codeNoeMalekiat")
                        .HasColumnType("bigint");

                    b.HasKey("Identity");

                    b.ToTable("Estelam");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.EventLogFilter", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogBarayeGozarAzHaddeAstaneyeBohraneMomayezi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogBarayeGozarAzHaddeAstaneyeHoshdareMomayezi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogBarayeHarGooneTalasheEhrazeHoviateChandGaneyeKarbar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogBarayeRaddeRamzeObour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MustLoginBeLogged")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identity");

                    b.ToTable("EventLogFilter");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.EventLogThreshold", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsAuditsLogWarningSmsSent")
                        .HasColumnType("int");

                    b.Property<int>("IsUserActivityLogWarningSmsSent")
                        .HasColumnType("int");

                    b.Property<int>("IsUserLoginLogWarningSmsSent")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsersActivityLogCritical")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsersActivityLogWarning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsersAuditsLogCritical")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsersAuditsLogWarning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsersLoginLogCritical")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsersLoginLogWarning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identity");

                    b.ToTable("EventLogThreshold");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.Expert", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateVisit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestNumber")
                        .HasColumnType("int");

                    b.HasKey("Identity");

                    b.ToTable("Expert");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.History", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<string>("CNosazi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("name_form")
                        .HasColumnType("int");

                    b.Property<string>("name_karbar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("noeamal")
                        .HasColumnType("int");

                    b.Property<string>("saat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sharh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("shod")
                        .HasColumnType("int");

                    b.Property<int?>("shop")
                        .HasColumnType("int");

                    b.Property<int?>("tarikh")
                        .HasColumnType("int");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identity");

                    b.ToTable("History");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.LogSMS", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DateTimeSMS")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileSMS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusSMS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextSMS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogSMS");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.Melk", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<double?>("ArzeshArse")
                        .HasColumnType("float");

                    b.Property<int?>("C_karbariAsli")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KarbariAsli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("asli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("azFari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bakhsh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("c_mahdodeh")
                        .HasColumnType("int");

                    b.Property<int?>("c_marhaleh")
                        .HasColumnType("int");

                    b.Property<int?>("c_noemelk")
                        .HasColumnType("int");

                    b.Property<int?>("c_noesanad")
                        .HasColumnType("int");

                    b.Property<int?>("c_vazmelk")
                        .HasColumnType("int");

                    b.Property<int?>("c_vazsanad")
                        .HasColumnType("int");

                    b.Property<string>("codeposti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mahdodeh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("marhaleh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("masahat_b")
                        .HasColumnType("float");

                    b.Property<double?>("masahat_e")
                        .HasColumnType("float");

                    b.Property<double?>("masahat_m")
                        .HasColumnType("float");

                    b.Property<double?>("masahat_s")
                        .HasColumnType("float");

                    b.Property<string>("noemelk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noesanad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pelakabi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("radif")
                        .HasColumnType("int");

                    b.Property<string>("sabti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("sh_Darkhast")
                        .HasColumnType("bigint");

                    b.Property<int>("shop")
                        .HasColumnType("int");

                    b.Property<string>("tafkiki")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("utmx")
                        .HasColumnType("float");

                    b.Property<double?>("utmy")
                        .HasColumnType("float");

                    b.Property<string>("vazmelk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vazsanad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identity");

                    b.ToTable("Melk");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.Parvandeh", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Formol")
                        .HasColumnType("int");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("apar")
                        .HasColumnType("int");

                    b.Property<int>("blok")
                        .HasColumnType("int");

                    b.Property<string>("codeN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("code_tree")
                        .HasColumnType("int");

                    b.Property<int>("hoze")
                        .HasColumnType("int");

                    b.Property<int>("idparent")
                        .HasColumnType("int");

                    b.Property<bool>("locked")
                        .HasColumnType("bit");

                    b.Property<int>("mantaghe")
                        .HasColumnType("int");

                    b.Property<int>("sakhteman")
                        .HasColumnType("int");

                    b.Property<int>("senfi")
                        .HasColumnType("int");

                    b.Property<int>("shomelk")
                        .HasColumnType("int");

                    b.Property<double>("shop")
                        .HasColumnType("float");

                    b.Property<bool>("sws")
                        .HasColumnType("bit");

                    b.HasKey("Identity");

                    b.ToTable("Parvandeh");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.Parvaneh", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("c_noeParvaneh")
                        .HasColumnType("int");

                    b.Property<double?>("masahat_m_esh_zamin")
                        .HasColumnType("float");

                    b.Property<double?>("masahat_m_s_tarakom")
                        .HasColumnType("float");

                    b.Property<string>("noe_parvaneh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sh_darkhast")
                        .HasColumnType("int");

                    b.Property<int>("sho_bimenameh")
                        .HasColumnType("int");

                    b.Property<double>("sho_parvaneh")
                        .HasColumnType("float");

                    b.Property<int>("shop")
                        .HasColumnType("int");

                    b.Property<DateTime?>("tarikh_e_bimeh")
                        .HasColumnType("datetime2");

                    b.Property<string>("tarikh_end_amaliat_s")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("tarikh_parvaneh")
                        .HasColumnType("datetime2");

                    b.Property<string>("tozihat_parvaneh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identity");

                    b.ToTable("Parvaneh");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.RolePermission", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Identity");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.RoleRestriction", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Identity");

                    b.ToTable("RoleRestrictions");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.Sakhteman", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<double?>("ArzeshAyan")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MasahatArse")
                        .HasColumnType("float");

                    b.Property<double?>("MasahatZirbana")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoeSakhteman")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoeSaze")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TarikhEhdas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TedadTabaghe")
                        .HasColumnType("float");

                    b.Property<int?>("c_NoeSakhteman")
                        .HasColumnType("int");

                    b.Property<int?>("c_NoeSaze")
                        .HasColumnType("int");

                    b.Property<int?>("c_marhaleh")
                        .HasColumnType("int");

                    b.Property<int?>("c_noenama")
                        .HasColumnType("int");

                    b.Property<int?>("c_noesaghf")
                        .HasColumnType("int");

                    b.Property<string>("marhaleh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("masahatkol")
                        .HasColumnType("float");

                    b.Property<string>("noenama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noesaghf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("radif")
                        .HasColumnType("int");

                    b.Property<double?>("satheshghal")
                        .HasColumnType("float");

                    b.Property<long?>("sh_Darkhast")
                        .HasColumnType("bigint");

                    b.Property<int>("shop")
                        .HasColumnType("int");

                    b.Property<double?>("tarakom")
                        .HasColumnType("float");

                    b.HasKey("Identity");

                    b.ToTable("Sakhteman");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.Tarifha", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhatemeSessionAfterMinute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaximumAccessDenied")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaximumSessions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestRateLimitter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RetryLoginCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sms_pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sms_shomare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sms_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identity");

                    b.ToTable("Tarifha");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.UserLogined", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsViewer")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LogoutDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identity");

                    b.ToTable("UserLogined");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.UserPermission", b =>
                {
                    b.Property<long>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identity"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Identity");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermission");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserSession");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.WeakPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("WeakPasswordText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeakPassword");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.ApplicationUserRole", b =>
                {
                    b.HasOne("FormerUrban_Afta.DataAccess.Model.CostumIdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormerUrban_Afta.DataAccess.Model.CostumIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.RolePermission", b =>
                {
                    b.HasOne("FormerUrban_Afta.DataAccess.Model.CostumIdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FormerUrban_Afta.DataAccess.Model.UserPermission", b =>
                {
                    b.HasOne("FormerUrban_Afta.DataAccess.Model.CostumIdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("FormerUrban_Afta.DataAccess.Model.CostumIdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FormerUrban_Afta.DataAccess.Model.CostumIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FormerUrban_Afta.DataAccess.Model.CostumIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FormerUrban_Afta.DataAccess.Model.CostumIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
